name: ci

on:
  push:
    tags:
      - "*"
    branches:
      - main
      - development
  pull_request:

jobs:
  code_check:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5.1.0
        with:
          python-version: 3.11
      - name: install_tools
        run: pip install -r ./code_check_req.txt
      - name: run_code_check
        run: bash code_check.sh

  unit_tests:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5.1.0
        with:
          python-version: 3.11
      - uses: conda-incubator/setup-miniconda@v3
        with:
          python-version: 3.11
          activate-environment: CondaDependencyCleaner
      - shell: bash -el {0}
        run: |
          conda init
          conda activate CondaDependencyCleaner
          conda install conda
          pip install -r ./tests/requirements.txt
          pip install .
      - name: run pytest
        run: python -m pytest -v
