name: ci

on:
  push:
    tags:
      - "*"
    branches:
      - main
      - development
  pull_request:

jobs:
  code_check:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5.1.0
        with:
          python-version: 3.11
      - name: install_tools
        run: pip install -r ./code_check_req.txt
      - name: run_code_check
        run: bash code_check.sh

  unit_tests:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        python-version: ["3.10", "3.11"]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5.1.0
        with:
          python-version: ${{ matrix.python-version }}
      - uses: conda-incubator/setup-miniconda@v3
        with:
          python-version: ${{ matrix.python-version }}
          activate-environment: CondaDependencyCleaner
      - name: install CDC
        shell: bash -el {0}
        run: |
          conda init
          conda activate CondaDependencyCleaner
          conda install conda
          pip install .
          pip install -r ./tests/requirements.txt
      - name: run pytest
        shell: bash -el {0}
        run: pytest -v

  build_wheels:
    runs-on: ubuntu-20.04
    needs: [unit_tests]
    strategy:
      matrix:
        python-version: [ "3.10", "3.11" ]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5.1.0
        with:
          python-version: ${{ matrix.python-version }}
      - name: Build wheels
        run:  pip install --upgrade build && python -m build --wheel
      - uses: actions/upload-artifact@v3
        with:
          name: dist
          path: ./dist/**/*.whl

  publish:
    runs-on: ubuntu-22.04
    if: startsWith(github.ref, 'refs/tags/')
    needs: [build_wheels]
    environment:
      name: publish
    permissions:
      id-token: write
    steps:
      - name: Download dist artifact
        uses: actions/download-artifact@v3
        with:
          name: dist
          path: dist
      - name: Publish package distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          packages-dir: dist/conda_dependency_cleaner-*.whl


